version: '3'
services:
  mysql8020:
    image: mysql:8.0.20
    ports:
      - 33060:33060
    volumes:
      - ./docker/mysql8020/data:/var/lib/mysql
      - ./docker/mysql8020/my.cnf:/etc/mysql/conf.d/my.cnf
    env_file:
      - ./base_env

