version: '3'
services:
  mysql8020:
    image: mysql:8.0.20
    ports:
      - 33061:3306
    volumes:
      - ./docker/mysql8020/data:/var/lib/mysql
      - ./docker/mysql8020/my.cnf:/etc/mysql/conf.d/my.cnf
    env_file:
      - ./base_env

  mysql8019:
    image: mysql:8.0.19
    ports:
      - 33062:3306
    volumes:
      - ./docker/mysql8019/data:/var/lib/mysql
      - ./docker/mysql8019/my.cnf:/etc/mysql/conf.d/my.cnf
    env_file:
      - ./base_env
  
  mysql8000:
    image: mysql:8.0.0
    ports:
      - 33063:3306
    volumes:
      - ./docker/mysql8000/data:/var/lib/mysql
      - ./docker/mysql8000/my.cnf:/etc/mysql/conf.d/my.cnf
    env_file:
      - ./base_env

  mysql5648:
    image: mysql:5.6.48
    ports:
      - 33064:3306
    volumes:
      - ./docker/mysql5648/data:/var/lib/mysql
    env_file:
      - ./base_env

  mysql5719:
    image: mysql:5.7.19
    ports:
      - 33065:3306
    volumes:
      - ./docker/mysql5719/data:/var/lib/mysql
    env_file:
      - ./base_env
