version: '3'
services:
  mysql8020:
    image: mysql:8.0.20
    ports:
      - 33060:3306
    volumes:
      - ./docker/mysql8020/data:/var/lib/mysql
      - ./docker/mysql8020/my.cnf:/etc/mysql/conf.d/my.cnf
    env_file:
      - ./base_env

  mysql8019:
    image: mysql:8.0.19
    ports:
      - 33069:3306
    volumes:
      - ./docker/mysql8019/data:/var/lib/mysql
      - ./docker/mysql8019/my.cnf:/etc/mysql/conf.d/my.cnf
    env_file:
      - ./base_env
  
  mysql8000:
    image: mysql:8.0.0
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql8000/data:/var/lib/mysql
      - ./docker/mysql8000/my.cnf:/etc/mysql/conf.d/my.cnf
    env_file:
      - ./base_env

  mysql5648:
    image: mysql:5.6.48
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql5648/data:/var/lib/mysql
    env_file:
      - ./base_env

  mysql5719:
    image: mysql:5.7.19
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql5719/data:/var/lib/mysql
    env_file:
      - ./base_env

  mysql5726:
    image: mysql:5.7.26
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql5726/data:/var/lib/mysql
    env_file:
      - ./base_env
  
  mysql8015:
    image: mysql:8.0.15
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql8015/data:/var/lib/mysql
    env_file:
      - ./base_env

  mysql8016:
    image: mysql:8.0.16
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql8016/data:/var/lib/mysql
    env_file:
      - ./base_env
  mysql8021:
    image: mysql:8.0.21
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql8021/data:/var/lib/mysql
      - ./docker/mysql8021/my.cnf:/etc/mysql/conf.d/my.cnf
    env_file:
      - ./base_env
  mysql8022:
    image: mysql:8.0.22
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql8022/data:/var/lib/mysql
      - ./docker/mysql8022/my.cnf:/etc/mysql/conf.d/my.cnf
    env_file:
      - ./base_env
  mysql8023:
    image: mysql:8.0.23
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql8023/data:/var/lib/mysql
      - ./docker/mysql8023/my.cnf:/etc/mysql/conf.d/my.cnf
    env_file:
      - ./base_env
  mysql8018:
    image: mysql:8.0.18
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql8018/data:/var/lib/mysql
      - ./docker/mysql8018/my.cnf:/etc/mysql/conf.d/my.cnf
    env_file:
      - ./base_env
  mysql8025:
    image: mysql:8.0.25
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql8025/data:/var/lib/mysql
      - ./docker/mysql8025/my.cnf:/etc/mysql/conf.d/my.cnf
    env_file:
      - ./base_env
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
  mysql8026:
    image: mysql:8.0.26
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql8026/data:/var/lib/mysql
      - ./docker/mysql8026/my.cnf:/etc/mysql/conf.d/my.cnf
    env_file:
      - ./base_env
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
  mysql8028:
    image: mysql:8.0.28
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql8028/data:/var/lib/mysql
      - ./docker/mysql8028/my.cnf:/etc/mysql/conf.d/my.cnf
    env_file:
      - ./base_env
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
